services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - 5432:5432

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    depends_on:
      - kong-database

  kong:
    restart: always
    image: kong:3.6
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
      - kong-migrations
    ports:
      - "8000:8000"  # Public proxy port
      - "8001:8001"  # Admin API (secure this!)
  
  fastapi:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    restart: always

  # Example: PostHog (adjust as needed)
  posthog:
    image: posthog/posthog:latest
    ports:
      - "8005:8005"
    environment:
      SECRET_KEY: yt1BaekASDKO4OnrZ-0LqwvGLV4lQeJZaV6fIn7UMekAYMFV6y_v8QgWALUzOliP
      DATABASE_URL: "postgres://kong:kong@kong-database:5432/kong"
      REDIS_URL: "redis://redis:6379"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_SECURE: "false"
    depends_on:
      - kong-database
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
  
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "9000:9000"    # Native protocol
      - "8123:8123"    # HTTP interface
      - "9009:9009"    # Interserver communication
      - "9440:9440"    # HTTPS (what PostHog expects by default)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""

