services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - 5432:5432

  kong-migrations:
    image: kong:3.6
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: kong
    depends_on:
      - kong-database

  kong:
    restart: always
    image: kong:3.6
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:80, 0.0.0.0:443 ssl
      KONG_SSL_CERT: /certs/fullchain.pem
      KONG_SSL_CERT_KEY: /certs/privkey.pem
    depends_on:
      - kong-database
      - kong-migrations
    ports:
      - "8000:8000"
      - "8443:8443"
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs:ro

  fastapi-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi
    ports:
      - "5433:5432"  # Exposes on 5433 locally, inside Docker use service name 'fastapi-db'
    volumes:
      - fastapi-db-data:/var/lib/postgresql/data
  
  fastapi:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - fastapi-db
    environment:
      DATABASE_URL: postgresql://fastapi:fastapi@fastapi-db:5432/fastapi

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  konga:
    image: pantsel/konga
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong 
      DB_PASSWORD: kong
      DB_DATABASE: konga

volumes:
  fastapi-db-data: