services:
  kong:
    restart: always
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl, 0.0.0.0:80, 0.0.0.0:443 ssl
      KONG_SSL_CERT: /certs/fullchain.pem
      KONG_SSL_CERT_KEY: /certs/privkey.pem
    ports:
      - "8000:8000"
      - "8443:8443"
      - "80:80"
      - "443:443"
      - "8001:8001" 
    volumes:
      - ./certs:/certs:ro
      - ./kong-config:/kong/declarative:ro

  fastapi-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi      
    ports:
      - "5433:5432"
    volumes:
      - fastapi-db-data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .                  
      dockerfile: backend/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --log-level debug
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - fastapi-db
    environment:
      DATABASE_URL: postgresql://fastapi:fastapi@fastapi-db:5432/fastapi
    env_file:
      - ./backend/.env

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  fastapi-db-data: