"""init

Revision ID: 78564a655399
Revises: 
Create Date: 2025-07-12 22:36:14.466056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78564a655399'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('demo', 'pro', 'trial', 'banned', name='usertier'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('upgraded_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_accounts_machine_id'), 'machine_accounts', ['machine_id'], unique=True)
    op.create_table('usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine_accounts.machine_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'feature_name', name='_machine_feature_uc')
    )
    op.create_index(op.f('ix_usage_stats_machine_id'), 'usage_stats', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_stats_machine_id'), table_name='usage_stats')
    op.drop_table('usage_stats')
    op.drop_index(op.f('ix_machine_accounts_machine_id'), table_name='machine_accounts')
    op.drop_table('machine_accounts')
    # ### end Alembic commands ###
